# Generated by Django 4.1.3 on 2023-05-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_course_preferences_user_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='course_preferences',
        ),
    ]
